apiVersion: v1
kind: Service
metadata:
  name: emails-svc
  labels:
    app: emails-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: grpc
  selector:
    app: emails
    version: v1
