// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: emailmgmt/email.proto

package emailmgmt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmailManagementClient is the client API for EmailManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailManagementClient interface {
	CreateNewEmail(ctx context.Context, in *NewEmail, opts ...grpc.CallOption) (*NewEmailResponse, error)
}

type emailManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailManagementClient(cc grpc.ClientConnInterface) EmailManagementClient {
	return &emailManagementClient{cc}
}

func (c *emailManagementClient) CreateNewEmail(ctx context.Context, in *NewEmail, opts ...grpc.CallOption) (*NewEmailResponse, error) {
	out := new(NewEmailResponse)
	err := c.cc.Invoke(ctx, "/emailmgmt.EmailManagement/CreateNewEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailManagementServer is the server API for EmailManagement service.
// All implementations must embed UnimplementedEmailManagementServer
// for forward compatibility
type EmailManagementServer interface {
	CreateNewEmail(context.Context, *NewEmail) (*NewEmailResponse, error)
	mustEmbedUnimplementedEmailManagementServer()
}

// UnimplementedEmailManagementServer must be embedded to have forward compatible implementations.
type UnimplementedEmailManagementServer struct {
}

func (UnimplementedEmailManagementServer) CreateNewEmail(context.Context, *NewEmail) (*NewEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewEmail not implemented")
}
func (UnimplementedEmailManagementServer) mustEmbedUnimplementedEmailManagementServer() {}

// UnsafeEmailManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailManagementServer will
// result in compilation errors.
type UnsafeEmailManagementServer interface {
	mustEmbedUnimplementedEmailManagementServer()
}

func RegisterEmailManagementServer(s grpc.ServiceRegistrar, srv EmailManagementServer) {
	s.RegisterService(&EmailManagement_ServiceDesc, srv)
}

func _EmailManagement_CreateNewEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEmail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailManagementServer).CreateNewEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emailmgmt.EmailManagement/CreateNewEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailManagementServer).CreateNewEmail(ctx, req.(*NewEmail))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailManagement_ServiceDesc is the grpc.ServiceDesc for EmailManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emailmgmt.EmailManagement",
	HandlerType: (*EmailManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewEmail",
			Handler:    _EmailManagement_CreateNewEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emailmgmt/email.proto",
}
